version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: x64
install:
- cmd: git submodule update --init eigen src/test/googletest
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -DUSE_CUDA=OFF -DUSE_EIGEN=ON -DBUILD_TESTS=ON -G "Visual Studio 14 2015 Win64"
build:
  project: build/thundersvm.sln
  parallel: true
  verbosity: quiet
test: off
artifacts:
- path: build\bin\
  name: thundersvm